### ISSUE TITLE
Guessing wrong hotspot interface (ifb0 instead of wlan2)

### ISSUE THREAD

**Issue by djpohly** [slowscript/warpinator-android#144]
When opening Warpinator with my phone's hotspot enabled, I get the error "Network unavailable - try hotspot?" and the "Failed to initialize service" popup, with an IllegalArgumentException "IP Address is invalid".

* Warpinator version: 1.7.1 from F-Droid
* Device: OnePlus 12R
* OS: OxygenOS 14 (stock)

## Details

From reading the logcat, it looks like Warpinator is choosing `ifb0` as its "some random active" interface guess, (correctly) getting null for the IPv4 address, and then trying to call `getHostAddress()` on that:

<details><summary>Excerpt from <code>logcat</code> (filtered by PID)</summary>

    W libc    : Access denied finding property "wifi.interface"
    D Utils   : Selected interface: ifb0
    E Utils   : Couldn't get IP address
    E Utils   : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.getHostAddress()' on a null object reference
    E Utils   : 	at slowscript.warpinator.Utils.getIPAddress(Utils.java:140)
    E Utils   : 	at slowscript.warpinator.MainService.onStartCommand(MainService.java:125)
    E Utils   : 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5198)
    E Utils   : 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
    E Utils   : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2548)
    E Utils   : 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E Utils   : 	at android.os.Looper.loopOnce(Looper.java:255)
    E Utils   : 	at android.os.Looper.loop(Looper.java:364)
    E Utils   : 	at android.app.ActivityThread.main(ActivityThread.java:8979)
    E Utils   : 	at java.lang.reflect.Method.invoke(Native Method)
    E Utils   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    E Utils   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
    D AUTH    : Loading server certificate...
    D AUTH    : Creating new server certificate...
    W libc    : Access denied finding property "wifi.interface"
    D Utils   : Selected interface: ifb0
    E Utils   : Couldn't get IP address
    E Utils   : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.getHostAddress()' on a null object reference
    E Utils   : 	at slowscript.warpinator.Utils.getIPAddress(Utils.java:140)
    E Utils   : 	at slowscript.warpinator.Authenticator.getServerCertificate(Authenticator.java:109)
    E Utils   : 	at slowscript.warpinator.MainService.onStartCommand(MainService.java:142)
    E Utils   : 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5198)
    E Utils   : 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
    E Utils   : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2548)
    E Utils   : 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E Utils   : 	at android.os.Looper.loopOnce(Looper.java:255)
    E Utils   : 	at android.os.Looper.loop(Looper.java:364)
    E Utils   : 	at android.app.ActivityThread.main(ActivityThread.java:8979)
    E Utils   : 	at java.lang.reflect.Method.invoke(Native Method)
    E Utils   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    E Utils   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
    E AUTH    : Failed to create certificate
    E AUTH    : java.lang.IllegalArgumentException: IP Address is invalid
    E AUTH    : 	at org.bouncycastle.asn1.x509.GeneralName.<init>(Unknown Source:287)
    E AUTH    : 	at slowscript.warpinator.Authenticator.getServerCertificate(Authenticator.java:235)
    E AUTH    : 	at slowscript.warpinator.MainService.onStartCommand(MainService.java:142)
    E AUTH    : 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5198)
    E AUTH    : 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
    E AUTH    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2548)
    E AUTH    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E AUTH    : 	at android.os.Looper.loopOnce(Looper.java:255)
    E AUTH    : 	at android.os.Looper.loop(Looper.java:364)
    E AUTH    : 	at android.app.ActivityThread.main(ActivityThread.java:8979)
    E AUTH    : 	at java.lang.reflect.Method.invoke(Native Method)
    E AUTH    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    E AUTH    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
    W SERVICE : Server will not start due to error

</details>

The correct interface on my device would be `wlan2`, as shown by iproute2.

<details><summary>Excerpt from <code>ip address</code></summary>

    3: ifb0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 32
        link/ether 02:c0:92:b7:8d:6c brd ff:ff:ff:ff:ff:ff
        inet6 fe80::c0:92ff:feb7:8d6c/64 scope link 
           valid_lft forever preferred_lft forever
    [...]
    27: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 3000
        link/ether 6e:27:27:8b:2b:16 brd ff:ff:ff:ff:ff:ff
    [...]
    68: wlan2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
        link/ether 46:5f:13:6a:cc:f7 brd ff:ff:ff:ff:ff:ff
        inet 192.168.66.54/24 brd 192.168.66.255 scope global wlan2
           valid_lft forever preferred_lft forever
        inet6 2600:1008:b120:6577::c5/64 scope global 
           valid_lft forever preferred_lft forever
        inet6 fe80::445f:13ff:fe6a:ccf7/64 scope link 
           valid_lft forever preferred_lft forever

</details>

This device also has a vendor-specific property that identifies the hotspot interface and doesn't require privilege to read (noting the "access denied" from logcat):

    # getprop wifi.interface
    wlan0
    # getprop vendor.oplus.sap.interface
    wlan2
    $ getprop wifi.interface
    
    $ getprop vendor.oplus.sap.interface
    wlan2

## Solution(s)

From what I can tell, any of the following would solve the problem on my device (they may all be worth considering):

 1. Exclude "ifb" in addition to "dummy" and "rmnet" in [`Utils.getActiveIface()`](https://github.com/slowscript/warpinator-android/blob/7819926eff29508001f2bf081a8de6ebb8510813/app/src/main/java/slowscript/warpinator/Utils.java#L131).  (IFB links are [virtual interfaces for traffic shaping](https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#ifb).)
 2. Skip devices with no IPv4 address in [`Utils.getActiveIface()`](https://github.com/slowscript/warpinator-android/blob/7819926eff29508001f2bf081a8de6ebb8510813/app/src/main/java/slowscript/warpinator/Utils.java#L131).
 3. If you don't mind adding vendor-specific workarounds, check `vendor.oplus.sap.interface` before `wifi.interface` in [`Utils.getWifiInterface()`](https://github.com/slowscript/warpinator-android/blob/7819926eff29508001f2bf081a8de6ebb8510813/app/src/main/java/slowscript/warpinator/Utils.java#L147).

**Comment by slowscript** [comment]
Thank you so much for the detailed description and proposed solutions. I went with options 1 and 2, hopefully it will handle most similar cases, I'd prefer to not have to add code specific for each problematic vendor (or device).

Also, sorry for responding so late, unfortunately I was very busy at the time and then I forgot that it's here. I'm working on Warpinator again now and soon will release a new version. If my fix didn't help, feel free to reopen. I don't have a OnePlus device to test.
